#!/usr/bin/php
<?php

echo <<<EOF
    _                    _   ___        __
   / \   __ _  ___ _ __ | |_|_ _|_ __  / _| ___ _ __ 
  / _ \ / _` |/ _ \ '_ \| __|| || '_ \| |_ / _ \ '__|
 / ___ \ (_| |  __/ | | | |_ | || | | |  _|  __/ |
/_/   \_\__, |\___|_| |_|\__|___|_| |_|_|  \___|_|
        |___/

@author Joe Persie
@release 0.0.2
EOF;

require_once(dirname(__FILE__) . '/core/bootload.php');

$haltProcess = FALSE;

$agent = ObjectRegistry::getByRegistryKey('AgentInfer');

while($haltProcess == FALSE)
{
    echo '...' . "\n";

    $agent->doProcessing();

    $haltProcess = $agent->hasShutdownSignal();
      
    sleep(5);
}

echo "\r\n SHUTTING DOWN...\r\n";

$agent->getState()->takeSnapshot();
