#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/core/bootload.php');

$haltProcess = FALSE;

$state = ObjectRegistry::getByRegistryKey('State');

$agent = ObjectRegistry::getByRegistryKey('AgentInfer');

while($haltProcess == FALSE)
{
    echo '...' . "\n";

    $agent->doProcessing();

    $haltProcess = $agent->hasShutdownSignal();
      
    sleep(5);
}

$state->takeSnapshot();
