#!/usr/bin/env php
<?php
require_once(dirname(__FILE__) . '/../../bootload.php');

$debugMode = false;

stream_set_blocking(STDIN, 0);

const TIMEOUT_SECONDS = 3;

exec("pgrep agentinferd", $pids);

if(empty($pids)) {
  exec('./../../agentinferd > agent.log 2>&1 & echo $!');
}

$agent = ObjectRegistry::getByRegistryKey('AgentInfer');

do {

    $message = trim(fgets(STDIN));

    if(!empty($message)) {

        $msg = $agent->submitMsg($message,'agent');

        if(!empty($msg) && $debugMode) {
            var_dump("MsgSubmitted");
            echo var_export($msg, true);
        }
    }

    $agentResponse = $agent->getResponse();

    if(!empty($agentResponse))
    {
        if($debugMode) {
            var_dump("AgentResponse");
            echo var_export($agentResponse, true);
        }
        else {
            echo "Agent: {$agentResponse->msg} \r\n";
        } 
    }

    sleep(TIMEOUT_SECONDS);

} while($message !== "SHUTDOWN"); 
